---
kind: Namespace
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: null-web
  namespace: web
spec:
  selector:
    matchLabels:
      app: null-web
  template:
    metadata:
      labels:
        app: null-web
    spec:
      containers: 
      - name: null-web
        image: nullchannel/nullcloud-frontend:5a73d02301b3a3228cdf7beaec5bc8f346242922
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

