resources:
- ../config/default/

images:
- name: nullchannel/eddington-null-operator
  newTag: 7d3945bed677f042a8048443602e07219018ff97
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
