resources:
- ../config/default/

images:
- name: nullchannel/eddington-null-operator
  newTag: 7b99e049b89e2ae130ddb76179025a40d38b47d5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
