---
kind: Namespace
apiVersion: v1
metadata:
  name: web
  labels:
    name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-ui
spec:
  selector:
    matchLabels:
      app: eddington-ui
  template:
    metadata:
      labels:
        app: eddington-ui
    spec:
      containers: 
      - name: eddington-ui
        image: nullchannel/eddington-ui:01575d4c12345d8fe58c0007c07e917dbd5c75bc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

