apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.1.1.10
      user: root
      port: 22
      keyPath: /home/marek/.ssh/k0s-certs/k0s 
    role: controller+worker
  - ssh:
      address: 10.1.2.2
      user: root
      port: 22
      keyPath: /home/marek/.ssh/k0s-certs/k0s 
    role: worker
  - ssh:
      address: 10.1.2.3
      user: root
      port: 22
      keyPath: /home/marek/.ssh/k0s-certs/k0s 
    role: worker
  k0s:
    version: 1.26.0+k0s.0
    dynamicConfig: false
