apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 10.1.1.10
      user: root
      port: 22
      keyPath: /Users/marycounts/.ssh/id_ed25519 
    role: controller+worker
  - ssh:
      address: 10.1.2.2
      user: root
      port: 22
      keyPath: /Users/marycounts/.ssh/id_ed25519 
    role: worker
  - ssh:
      address: 10.1.2.3
      user: root
      port: 22
      keyPath: /Users/marycounts/.ssh/id_ed25519 
    role: worker
  k0s:
    version: 1.24.4+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.2.1.1/18
          serviceCIDR: 10.96.0.0/12
          provider: kuberouter
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
