apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: null-website 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
  project: null-cloud
  source:
    path: k8s
    repoURL: https://github.com/null-channel/null-web
    targetRevision: argo-deployments
    directory:
      recurse: true
  syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true
