cookies:
  domain: hungry-jennings-4s54dkzkv7.projects.oryapis.com
  path: /
  same_site: Lax
courier:
  smtp:
    from_name: Marek Counts's Project via Ory
  templates:
    recovery:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    recovery_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
feature_flags:
  cacheable_sessions: false
identity:
  default_schema_id: preset://email
  schemas:
  - id: preset://email
    url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9pZGVudGl0eS5lbWFpbC5zY2hlbWEuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwKICAidGl0bGUiOiAiUGVyc29uIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJwcm9wZXJ0aWVzIjogewogICAgInRyYWl0cyI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgImVtYWlsIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJmb3JtYXQiOiAiZW1haWwiLAogICAgICAgICAgInRpdGxlIjogIkUtTWFpbCIsCiAgICAgICAgICAib3J5LnNoL2tyYXRvcyI6IHsKICAgICAgICAgICAgImNyZWRlbnRpYWxzIjogewogICAgICAgICAgICAgICJwYXNzd29yZCI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgIndlYmF1dGhuIjogewogICAgICAgICAgICAgICAgImlkZW50aWZpZXIiOiB0cnVlCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAidG90cCI6IHsKICAgICAgICAgICAgICAgICJhY2NvdW50X25hbWUiOiB0cnVlCiAgICAgICAgICAgICAgfQogICAgICAgICAgICB9LAogICAgICAgICAgICAicmVjb3ZlcnkiOiB7CiAgICAgICAgICAgICAgInZpYSI6ICJlbWFpbCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInZlcmlmaWNhdGlvbiI6IHsKICAgICAgICAgICAgICAidmlhIjogImVtYWlsIgogICAgICAgICAgICB9CiAgICAgICAgICB9LAogICAgICAgICAgIm1heExlbmd0aCI6IDMyMAogICAgICAgIH0KICAgICAgfSwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJlbWFpbCIKICAgICAgXSwKICAgICAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogZmFsc2UKICAgIH0KICB9Cn0K
oauth2_provider:
  override_return_to: false
selfservice:
  allowed_return_urls:
  - https://hungry-jennings-4s54dkzkv7.projects.oryapis.com
  default_browser_return_url: /ui/welcome
  flows:
    error:
      ui_url: /ui/error
    login:
      after:
        hooks: []
        oidc:
          hooks: []
        password:
          hooks: []
        webauthn:
          hooks: []
      before:
        hooks: []
      ui_url: /ui/login
    logout:
      after: {}
    recovery:
      after:
        hooks: []
      before:
        hooks: []
      enabled: true
      notify_unknown_recipients: false
      ui_url: /ui/recovery
      use: code
    registration:
      after:
        hooks: []
        oidc:
          hooks:
          - hook: web_hook
            config:
              url: https://nullcloud.io/ory/webhook
              method: POST
              body: base64://ZnVuY3Rpb24oY3R4KSB7IAogIHVzZXJJZDogY3R4LmlkZW50aXR5LmlkLAogIHRyYWl0czogewogICAgZW1haWw6IGN0eC5pZGVudGl0eS50cmFpdHMuZW1haWwsCiAgICBuYW1lOiBjdHguaWRlbnRpdHkudHJhaXRzLm5hbWUsCiAgICBuZXdzbGV0dGVyQ29uc2VudDogY3R4LmlkZW50aXR5LnRyYWl0cy5jb25zZW50Lm5ld3NsZXR0ZXIsCiAgfSwKfQo=
              response:
                ignore: false
                parse: false
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: marekssecret
                  in: header # alternatively "cookie"
          - hook: session
        password:
          hooks:
          - hook: web_hook
            config:
              url: https://nullcloud.io/ory/webhook
              method: POST
              body: base64://ZnVuY3Rpb24oY3R4KSB7IAogIHVzZXJfaWQ6IGN0eC5pZGVudGl0eS5pZCwKICB0cmFpdHM6IHsKICAgIGVtYWlsOiBjdHguaWRlbnRpdHkudHJhaXRzLmVtYWlsLAogICAgbmFtZTogY3R4LmlkZW50aXR5LnRyYWl0cy5uYW1lLAogICAgbmV3c2xldHRlckNvbnNlbnQ6IGN0eC5pZGVudGl0eS50cmFpdHMuY29uc2VudC5uZXdzbGV0dGVyLAogIH0sCn0K
              response:
                ignore: false
                parse: false
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: marekssecret
                  in: header # alternatively "cookie"
          - hook: session
        webauthn:
          hooks:
          - hook: session
      before:
        hooks: []
      ui_url: /ui/registration
    settings:
      after:
        hooks: []
        password:
          hooks: []
        profile:
          hooks: []
      before:
        hooks: []
      privileged_session_max_age: 15m0s
      required_aal: highest_available
      ui_url: /ui/settings
    verification:
      after:
        hooks: []
      before:
        hooks: []
      enabled: true
      notify_unknown_recipients: false
      ui_url: /ui/verification
      use: code
  methods:
    code:
      config: {}
    link:
      config:
        base_url: ""
      enabled: true
    lookup_secret: {}
    oidc:
      config:
        providers: []
      enabled: false
    password:
      config: {}
    profile: {}
    totp:
      config:
        issuer: Marek Counts's Project
    webauthn:
      config:
        passwordless: false
        rp:
          display_name: Marek Counts's Project
          id: hungry-jennings-4s54dkzkv7.projects.oryapis.com
          origin: https://hungry-jennings-4s54dkzkv7.projects.oryapis.com
serve:
  admin:
    base_url: https://hungry-jennings-4s54dkzkv7.projects.oryapis.com/
    request_log:
      disable_for_health: true
  public:
    base_url: https://hungry-jennings-4s54dkzkv7.projects.oryapis.com/
    cors:
      enabled: false
    request_log:
      disable_for_health: true
session:
  cookie:
    domain: hungry-jennings-4s54dkzkv7.projects.oryapis.com
    name: ory_session_hungryjennings4s54dkzkv7
    path: /
    same_site: Lax
  lifespan: 72h0m0s
  whoami:
    required_aal: highest_available
