apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-api
spec:
  selector:
    matchLabels:
      app: eddington-api
  template:
    metadata:
      labels:
        app: eddington-api
    spec:
      containers: 
      - name: eddington-api
        image: nullchannel/eddington-api:fcb2c04aa2d25240f5df3427fb01bd90d0338ffa
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

