apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-api
spec:
  selector:
    matchLabels:
      app: eddington-api
  template:
    metadata:
      labels:
        app: eddington-api
    spec:
      containers: 
      - name: eddington-api
        image: nullchannel/eddington-api:8145e7a091476b31cbca7083d68f1513f5bee1c0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

