apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-api
spec:
  selector:
    matchLabels:
      app: eddington-api
  template:
    metadata:
      labels:
        app: eddington-api
    spec:
      containers: 
      - name: eddington-api
        image: nullchannel/eddington-api:826f68eed8a6bbde725631402d512b0160a65601
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

