apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder-go
  namespace: kpack-system
spec:
  serviceAccountName: tutorial-service-account
  tag: nullcloud-builder-go
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/go
