# permissions for end users to view nullapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nullapplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: null-operator
    app.kubernetes.io/part-of: null-operator
    app.kubernetes.io/managed-by: kustomize
  name: nullapplication-viewer-role
rules:
- apiGroups:
  - nullapp.io.nullcloud
  resources:
  - nullapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nullapp.io.nullcloud
  resources:
  - nullapplications/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
