apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-container-builder
  namespace: nullcloud-system
spec:
  selector:
    matchLabels:
      app: eddington-container-builder
  template:
    metadata:
      labels:
        app: eddington-container-builder
    spec:
      containers: 
      - name: eddington-container-builder
        image: nullchannel/eddington-container-builder:325dcee676b36bd35f329b7961661a1d6d3b8913
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        env:
          - name: REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                name: container-builder-config
                key: REGISTRY_URL
            
