apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-container-builder
  namespace: eddington-admin
spec:
  selector:
    matchLabels:
      app: eddington-container-builder
  template:
    metadata:
      labels:
        app: eddington-container-builder
    spec:
      volumes:
      - name: docker-socket
        hostPath:
          path: "/eddington/var/run"
          type: Directory
      - name: docker-config
        hostPath:
          path: "/eddington/var/lib/docker"
      containers: 
      - name: eddington-container-builder
        image: nullchannel/eddington-container-builder:latest
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
        env:
          - name: REGISTRY_URL
            valueFrom:
              configMapKeyRef:
                name: container-builder-config
                key: REGISTRY_URL
          - name: DOCKER_HOST
            valueFrom:
              configMapKeyRef:
                name: container-builder-config 
                key: DOCKER_HOST
        volumeMounts:
          - mountPath: "/eddington/var/run"
            name: docker-socket
            readOnly: false
          - mountPath: "/eddington/var/lib/docker"
            name: docker-config
            readOnly: false
            
