apiVersion: v1
kind: Service
metadata:
  name: eddington-container-builder
  namespace: nullcloud-system
spec:
  selector:
    app: eddington-container-builder
  ports:
  - port: 50051
    targetPort: 4040
