apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
  namespace: 1password
spec:
  project: default
  source:
    chart: 1password
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 1.16.1
    helm:
      releaseName: 1password
  destination:
    namespace: 1password