apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: null-cloud
  source:
    path: deployments/cert-manager
    repoURL: https://github.com/null-channel/nullcloud-deployments/
    targetRevision: HEAD
  syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true