apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: null-cloud
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: nullcloud-system
  project: null-cloud
  source:
    path: deployments/null-cloud/overlays/dev
    repoURL: https://github.com/null-channel/nullcloud-deployments/
    targetRevision: HEAD
  syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true
